// AUTO-GENERATED by scripts/gen-data-index.ts — DO NOT EDIT BY HAND.
// Regenerate with `npm run gen:index` (predev/prebuild do it for you). `npm run check:index`
// fails the build if this file is stale. Source of truth stays in the real data modules.
//
// Just the three numbers the landing map shows. Importing `data/reading` for these made the map —
// the DEFAULT route — a preload dependency of the whole 639 kB reading corpus (measured M1).
// The reading pages still import the real dataset; they are the routes that actually read texts.

export const READING_COUNTS = {
  categories: 22,
  categoriesWithTexts: 17,
  texts: 298,
} as const;
