/*
 * gen-data-index.ts — the META-SPLIT generator (standard §4.4, applied to the dictionary; M1).
 * Run: `npm run gen:index` (also runs automatically via `predev` / `prebuild`).
 *
 * WHY THIS EXISTS
 * The eager app shell needs three cheap things from the big corpora: the word count in the footer,
 * the reading counts on the landing map, and a searchable list of headwords. Importing the real
 * datasets for those pulled **899 kB of word cards + 639 kB of reading bodies** into the eager
 * entry chunk (measured M1: index chunk 1.39 MB). This script emits SLIM, generated modules the
 * shell can import instead; the full corpora stay behind lazy route chunks. PROJECT-BRIEF §6 calls
 * that separation the "scale guard" — at the 3,000-word target the eager alternative is ~6–8 MB.
 *
 * OUTPUTS (committed to the repo — `tsc -b` typechecks them, so they must always exist):
 *   src/data/words/index.generated.ts    slim WORD_INDEX (id · word · level · joined translations)
 *                                        + WORD_COUNTS
 *   src/data/reading/index.generated.ts  READING_COUNTS only (the landing map's three numbers)
 *   src/data/phrases.generated.ts        PHRASE_COUNTS — the Words-hub tab badges (V12)
 *
 * DELIBERATELY NOT IN THE WORD INDEX: `def`. Including both languages of every definition triples
 * the index (52 kB → 152 kB now, ~890 kB at 3,000 words) and would re-break the scale guard. Search
 * keeps its definition matching by lazily upgrading to the full corpus — see lib/search.ts
 * `primeWordCorpus()`. Adding a field here is cheap; adding a BIG field is not — measure first.
 *
 * `scripts/check-data-index.ts` re-runs this in memory and fails if the committed files differ, so a
 * words/reading wave can never ship a stale index.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { COLLOCATIONS } from '../src/data/collocations';
import { IDIOMS } from '../src/data/idioms';
import { IRREGULAR } from '../src/data/irregular';
import { modules } from '../src/data/modules/all';
import { a1Words } from '../src/data/words/a1';
import { customWords } from '../src/data/words/custom';
import { READING_CATEGORIES, READING_TEXTS } from '../src/data/reading';

const here = dirname(fileURLToPath(import.meta.url));

export const WORDS_INDEX_PATH = resolve(here, '../src/data/words/index.generated.ts');
export const READING_INDEX_PATH = resolve(here, '../src/data/reading/index.generated.ts');
// CHANGED (V12): the Words-hub tab badges. VocabTabs used to import WORDS + IDIOMS + IRREGULAR
// just to print five numbers — and VocabTabs renders on EVERY Words tab, so opening #/dictionary
// downloaded the whole idioms corpus. check:bundle cannot see it (all of this is behind
// React.lazy, so it never touches the EAGER graph): the split into per-tab chunks would have
// been silently cosmetic. Counts come from here now; the corpora stay in their own chunks.
export const PHRASES_COUNTS_PATH = resolve(here, '../src/data/phrases.generated.ts');
// CHANGED (M2): the module meta-split — nav meta, the aggregated drill set, and the per-module
// lazy-import map, all derived from src/data/modules/all.ts.
export const MODULE_META_PATH = resolve(here, '../src/data/meta.generated.ts');
export const DRILLS_PATH = resolve(here, '../src/data/drills.generated.ts');
export const MODULE_LOADERS_PATH = resolve(here, '../src/data/moduleLoaders.generated.ts');

const BANNER = `// AUTO-GENERATED by scripts/gen-data-index.ts — DO NOT EDIT BY HAND.
// Regenerate with \`npm run gen:index\` (predev/prebuild do it for you). \`npm run check:index\`
// fails the build if this file is stale. Source of truth stays in the real data modules.`;

/** JSON.stringify is the escaping authority here — never hand-roll quotes into generated code. */
const lit = (v: unknown): string => JSON.stringify(v);

function wordsModule(): string {
  const rows = [...a1Words, ...customWords].map(
    (w) =>
      `  { id: ${lit(w.id)}, word: ${lit(w.word)}, level: ${lit(w.level)}, translations: ${lit(
        w.translations.join(', '),
      )} },`,
  );
  return `${BANNER}
//
// The SLIM word index for the eager shell: enough for global search to rank headwords and UA
// translations, and for the footer count — without loading a single definition or example.
// \`translations\` is pre-joined (the only consumer displays and matches it as one string).
import type { Level } from '../types';

export type WordIndexEntry = {
  id: string;
  word: string;
  level: Level;
  /** UA translations, pre-joined with ", " — matched and displayed as one string. */
  translations: string;
};

export const WORD_COUNTS = {
  total: ${a1Words.length + customWords.length},
  a1: ${a1Words.length},
  custom: ${customWords.length},
} as const;

export const WORD_INDEX: readonly WordIndexEntry[] = [
${rows.join('\n')}
];
`;
}

function readingModule(): string {
  const withTexts = READING_CATEGORIES.filter((c) =>
    READING_TEXTS.some((t) => t.category === c.id),
  ).length;
  return `${BANNER}
//
// Just the three numbers the landing map shows. Importing \`data/reading\` for these made the map —
// the DEFAULT route — a preload dependency of the whole 639 kB reading corpus (measured M1).
// The reading pages still import the real dataset; they are the routes that actually read texts.

export const READING_COUNTS = {
  categories: ${READING_CATEGORIES.length},
  categoriesWithTexts: ${withTexts},
  texts: ${READING_TEXTS.length},
} as const;
`;
}

// ─────────────────────────── M2: the module meta-split ───────────────────────────
// Same principle as the dictionary, one level up. The shell (sidebar · landing map · global search ·
// module header + TOC) needs ~42 kB of nav meta; the bodies it never reads are 450 kB at 12/34
// authored. So: meta eagerly, bodies one lazy chunk at a time.

/** Nav meta for every module — the ONLY module data the eager shell may import. */
function metaModule(): string {
  const rows = modules.map((m) => {
    const meta = {
      id: m.id,
      num: m.num,
      section: m.section,
      order: m.order,
      level: m.level,
      ...(m.signature ? { signature: true } : {}),
      title: m.title,
      tagline: m.tagline,
      readMins: m.readMins,
      mentalModel: m.mentalModel,
      // `authored` is derived here so the shell never needs a body to answer "is this a stub?".
      authored: m.topics.length > 0,
      // Topic id + title only: the module TOC and search need these, blocks do NOT belong here.
      topics: m.topics.map((t) => ({ id: t.id, title: t.title })),
    };
    return `  ${lit(meta)},`;
  });
  const authored = modules.filter((m) => m.topics.length > 0).length;
  return `${BANNER}
//
// Nav META for all ${modules.length} modules (${authored} authored). This is a BUDGET, not a bag:
// it ships in the eager entry chunk on every page load. Topic BLOCKS, exercises, keyPoints,
// pitfalls, sources and seeAlso are deliberately absent — \`concepts.loadModule(id)\` fetches the
// real module from its own lazy chunk when a module page actually opens.
import type { Level, Localized } from './types';

export type TopicMeta = { id: string; title: Localized };

export type ModuleMeta = {
  id: string;
  num: number;
  section: string;
  order: number;
  level: Level;
  signature?: boolean;
  title: Localized;
  tagline: Localized;
  readMins: number;
  mentalModel: Localized;
  /** false = a navigable stub (no content authored yet). */
  authored: boolean;
  topics: readonly TopicMeta[];
};

export const MODULE_COUNTS = { total: ${modules.length}, authored: ${authored} } as const;

export const MODULE_META: readonly ModuleMeta[] = [
${rows.join('\n')}
];
`;
}

/**
 * Every drill from every module, in module order — for the #/practice hub, which aggregates across
 * ALL modules and would otherwise have to load all 34 bodies to find 181 exercises.
 *
 * Yes, this DUPLICATES the exercises that also live in the module files. That is the deliberate
 * trade: the alternative is #/practice pulling ~450 kB of topic prose to reach ~103 kB of drills.
 * The duplication is generated, never hand-edited, and `check:index` fails the build if it drifts;
 * the module files remain the SSOT and `check:data` validates them, not this file.
 */
function drillsModule(): string {
  const drills = modules.flatMap((m) =>
    (m.exercises ?? []).map((ex) => ({ ...ex, moduleId: m.id })),
  );
  return `${BANNER}
//
// ${drills.length} drills aggregated from ${modules.filter((m) => (m.exercises ?? []).length > 0).length} modules.
// \`moduleId\` is added so #/practice can link a drill back to where it is taught.
import type { Exercise } from './types';

export type Drill = Exercise & { moduleId: string };

export const DRILLS: readonly Drill[] = [
${drills.map((d) => `  ${lit(d)},`).join('\n')}
];
`;
}

/**
 * id → () => import(the module body). Literal specifiers on purpose: Vite/Rollup can only code-split
 * a dynamic import it can see statically, so this map must be generated, not built from a template
 * string at runtime. Stubs get no entry — they have no body to load.
 */
function moduleLoadersModule(): string {
  const authored = modules.filter((m) => m.topics.length > 0);
  const rows = authored.map((m) => {
    // Authored modules are exported as `mN` from `modules/<id>.ts` (the repo convention).
    const exportName = `m${m.num}`;
    return `  ${lit(m.id)}: () => import('./modules/${m.id}').then((mod) => mod.${exportName}),`;
  });
  return `${BANNER}
//
// One lazy chunk per authored module body (${authored.length} of ${modules.length}). Consumed by
// \`concepts.loadModule()\`; a stub id resolves to undefined there, which is what the module page
// renders as ComingSoon.
import type { Module } from './types';

export const moduleLoaders: Readonly<Record<string, () => Promise<Module>>> = {
${rows.join('\n')}
};
`;
}

/**
 * The five numbers the Words-hub tab bar shows. Deliberately counts, never entries: this module is
 * imported by a component that every Words route renders, so anything bigger than a number here
 * re-creates the exact regression it was written to remove.
 */
function phraseCountsModule(): string {
  const idioms = IDIOMS.filter((e) => e.kind === 'idiom').length;
  const phrasals = IDIOMS.filter((e) => e.kind === 'phrasal').length;
  return `${BANNER}
//
// Tab-badge counts for the Words hub (components/layout/VocabTabs.tsx). See gen-data-index.ts
// for why these are generated instead of read off the corpora.

export const PHRASE_COUNTS = {
  /** data/idioms.ts total — idioms + phrasal verbs. */
  expressions: ${IDIOMS.length},
  idioms: ${idioms},
  phrasals: ${phrasals},
  /** data/collocations.ts total (V12). */
  collocations: ${COLLOCATIONS.length},
  irregular: ${IRREGULAR.length},
} as const;
`;
}

/** The generated sources, as they should exist on disk. Shared with check-data-index.ts. */
export function generate(): { path: string; source: string }[] {
  return [
    { path: WORDS_INDEX_PATH, source: wordsModule() },
    { path: READING_INDEX_PATH, source: readingModule() },
    { path: PHRASES_COUNTS_PATH, source: phraseCountsModule() }, // CHANGED (V12)
    { path: MODULE_META_PATH, source: metaModule() },
    { path: DRILLS_PATH, source: drillsModule() },
    { path: MODULE_LOADERS_PATH, source: moduleLoadersModule() },
  ];
}

/** Read a generated file, or '' when it does not exist yet (first run / fresh clone). */
export function readGenerated(path: string): string {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
}

// Only write when run directly (check-data-index.ts imports `generate` without touching disk).
const isMain = process.argv[1] !== undefined && resolve(process.argv[1]) === resolve(here, 'gen-data-index.ts');
if (isMain) {
  let changed = 0;
  for (const { path, source } of generate()) {
    if (readGenerated(path) === source) continue;
    writeFileSync(path, source, 'utf8');
    changed++;
  }
  const authored = modules.filter((m) => m.topics.length > 0).length;
  console.log(
    `✓ gen:index — ${WORD_COUNTS_LOG()} · ${READING_TEXTS.length} reading texts in ${READING_CATEGORIES.length} categories` +
      ` · ${modules.length} modules (${authored} authored) · ${modules.flatMap((m) => m.exercises ?? []).length} drills` +
      ` · ${IDIOMS.length} expressions + ${COLLOCATIONS.length} collocations`
      + ` (${changed === 0 ? 'already up to date' : `${changed} file(s) rewritten`}).`,
  );
}

function WORD_COUNTS_LOG(): string {
  return `${a1Words.length + customWords.length} words (${a1Words.length} a1 + ${customWords.length} custom)`;
}
