/*
 * gen-data-index.ts — the META-SPLIT generator (standard §4.4, applied to the dictionary; M1).
 * Run: `npm run gen:index` (also runs automatically via `predev` / `prebuild`).
 *
 * WHY THIS EXISTS
 * The eager app shell needs three cheap things from the big corpora: the word count in the footer,
 * the reading counts on the landing map, and a searchable list of headwords. Importing the real
 * datasets for those pulled **899 kB of word cards + 639 kB of reading bodies** into the eager
 * entry chunk (measured M1: index chunk 1.39 MB). This script emits SLIM, generated modules the
 * shell can import instead; the full corpora stay behind lazy route chunks. PROJECT-BRIEF §6 calls
 * that separation the "scale guard" — at the 3,000-word target the eager alternative is ~6–8 MB.
 *
 * OUTPUTS (committed to the repo — `tsc -b` typechecks them, so they must always exist):
 *   src/data/words/index.generated.ts    slim WORD_INDEX (id · word · level · joined translations)
 *                                        + WORD_COUNTS
 *   src/data/reading/index.generated.ts  READING_COUNTS only (the landing map's three numbers)
 *
 * DELIBERATELY NOT IN THE WORD INDEX: `def`. Including both languages of every definition triples
 * the index (52 kB → 152 kB now, ~890 kB at 3,000 words) and would re-break the scale guard. Search
 * keeps its definition matching by lazily upgrading to the full corpus — see lib/search.ts
 * `primeWordCorpus()`. Adding a field here is cheap; adding a BIG field is not — measure first.
 *
 * `scripts/check-data-index.ts` re-runs this in memory and fails if the committed files differ, so a
 * words/reading wave can never ship a stale index.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { a1Words } from '../src/data/words/a1';
import { customWords } from '../src/data/words/custom';
import { READING_CATEGORIES, READING_TEXTS } from '../src/data/reading';

const here = dirname(fileURLToPath(import.meta.url));

export const WORDS_INDEX_PATH = resolve(here, '../src/data/words/index.generated.ts');
export const READING_INDEX_PATH = resolve(here, '../src/data/reading/index.generated.ts');

const BANNER = `// AUTO-GENERATED by scripts/gen-data-index.ts — DO NOT EDIT BY HAND.
// Regenerate with \`npm run gen:index\` (predev/prebuild do it for you). \`npm run check:index\`
// fails the build if this file is stale. Source of truth stays in the real data modules.`;

/** JSON.stringify is the escaping authority here — never hand-roll quotes into generated code. */
const lit = (v: unknown): string => JSON.stringify(v);

function wordsModule(): string {
  const rows = [...a1Words, ...customWords].map(
    (w) =>
      `  { id: ${lit(w.id)}, word: ${lit(w.word)}, level: ${lit(w.level)}, translations: ${lit(
        w.translations.join(', '),
      )} },`,
  );
  return `${BANNER}
//
// The SLIM word index for the eager shell: enough for global search to rank headwords and UA
// translations, and for the footer count — without loading a single definition or example.
// \`translations\` is pre-joined (the only consumer displays and matches it as one string).
import type { Level } from '../types';

export type WordIndexEntry = {
  id: string;
  word: string;
  level: Level;
  /** UA translations, pre-joined with ", " — matched and displayed as one string. */
  translations: string;
};

export const WORD_COUNTS = {
  total: ${a1Words.length + customWords.length},
  a1: ${a1Words.length},
  custom: ${customWords.length},
} as const;

export const WORD_INDEX: readonly WordIndexEntry[] = [
${rows.join('\n')}
];
`;
}

function readingModule(): string {
  const withTexts = READING_CATEGORIES.filter((c) =>
    READING_TEXTS.some((t) => t.category === c.id),
  ).length;
  return `${BANNER}
//
// Just the three numbers the landing map shows. Importing \`data/reading\` for these made the map —
// the DEFAULT route — a preload dependency of the whole 639 kB reading corpus (measured M1).
// The reading pages still import the real dataset; they are the routes that actually read texts.

export const READING_COUNTS = {
  categories: ${READING_CATEGORIES.length},
  categoriesWithTexts: ${withTexts},
  texts: ${READING_TEXTS.length},
} as const;
`;
}

/** The generated sources, as they should exist on disk. Shared with check-data-index.ts. */
export function generate(): { path: string; source: string }[] {
  return [
    { path: WORDS_INDEX_PATH, source: wordsModule() },
    { path: READING_INDEX_PATH, source: readingModule() },
  ];
}

/** Read a generated file, or '' when it does not exist yet (first run / fresh clone). */
export function readGenerated(path: string): string {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
}

// Only write when run directly (check-data-index.ts imports `generate` without touching disk).
const isMain = process.argv[1] !== undefined && resolve(process.argv[1]) === resolve(here, 'gen-data-index.ts');
if (isMain) {
  let changed = 0;
  for (const { path, source } of generate()) {
    if (readGenerated(path) === source) continue;
    writeFileSync(path, source, 'utf8');
    changed++;
  }
  console.log(
    `✓ gen:index — ${WORD_COUNTS_LOG()} · ${READING_TEXTS.length} reading texts in ${READING_CATEGORIES.length} categories` +
      ` (${changed === 0 ? 'already up to date' : `${changed} file(s) rewritten`}).`,
  );
}

function WORD_COUNTS_LOG(): string {
  return `${a1Words.length + customWords.length} words (${a1Words.length} a1 + ${customWords.length} custom)`;
}
