// AUTO-GENERATED by scripts/gen-data-index.ts — DO NOT EDIT BY HAND.
// Regenerate with `npm run gen:index` (predev/prebuild do it for you). `npm run check:index`
// fails the build if this file is stale. Source of truth stays in the real data modules.
//
// One lazy chunk per authored module body (12 of 34). Consumed by
// `concepts.loadModule()`; a stub id resolves to undefined there, which is what the module page
// renders as ComingSoon.
import type { Module } from './types';

export const moduleLoaders: Readonly<Record<string, () => Promise<Module>>> = {
  "m6-tense-system": () => import('./modules/m6-tense-system').then((mod) => mod.m6),
  "m7-present-simple-continuous": () => import('./modules/m7-present-simple-continuous').then((mod) => mod.m7),
  "m8-past-simple-continuous": () => import('./modules/m8-past-simple-continuous').then((mod) => mod.m8),
  "m9-future-forms": () => import('./modules/m9-future-forms').then((mod) => mod.m9),
  "m10-perfect-family": () => import('./modules/m10-perfect-family').then((mod) => mod.m10),
  "m11-choosing-narrative": () => import('./modules/m11-choosing-narrative').then((mod) => mod.m11),
  "m17-modal-system": () => import('./modules/m17-modal-system').then((mod) => mod.m17),
  "m18-ability-permission": () => import('./modules/m18-ability-permission').then((mod) => mod.m18),
  "m19-obligation-necessity": () => import('./modules/m19-obligation-necessity').then((mod) => mod.m19),
  "m20-advice-criticism": () => import('./modules/m20-advice-criticism').then((mod) => mod.m20),
  "m21-deduction-probability": () => import('./modules/m21-deduction-probability').then((mod) => mod.m21),
  "m22-requests-politeness": () => import('./modules/m22-requests-politeness').then((mod) => mod.m22),
};
