// AUTO-GENERATED by scripts/gen-data-index.ts — DO NOT EDIT BY HAND.
// Regenerate with `npm run gen:index` (predev/prebuild do it for you). `npm run check:index`
// fails the build if this file is stale. Source of truth stays in the real data modules.
//
// Tab-badge counts for the Words hub (components/layout/VocabTabs.tsx). See gen-data-index.ts
// for why these are generated instead of read off the corpora.

export const PHRASE_COUNTS = {
  /** data/idioms.ts total — idioms + phrasal verbs. */
  expressions: 262,
  idioms: 185,
  phrasals: 77,
  /** data/collocations.ts total (V12). */
  collocations: 203,
  irregular: 75,
} as const;
